language: python

python:
  - "3.6"

services:
  - docker
# command will excuate before any automation command
before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
